cards/urls.py
"""Url Configurations"""

from django.urls import path
from cards import views

urlpatterns = [
    # dashboard
    path('dashboard', views.DashboardView, name='dashboard'),
    path('deck/<int:deck_id>', views.DeckView, name='deck_detail'),
    # stats
    path('stats', views.ViewStats, name='stats'),
    path('stats/<int:deck_id>', views.CardQuestions, name='card_stats'),
    path('stats/<int:deck_id>/<int:question_id>/',
         views.QuestionStats, name='question_stat'),
    # upload data
    path('newdeck', views.CreateDeck, name='new_deck'),
    path('excel', views.ExcelUpload, name='excel_upload'),
    path('question', views.QuestionsView,
         name='question'),
    # modify data
    path('deck/recordscore', views.RecordScore, name='record_score'),
    path('delete_deck/<int:deck_id>',
         views.DeleteDeck, name='delete_deck'),
    path('delete_card/<int:deck_id>/<int:card_id>/>',
         views.DeleteCard, name='delete_card'),
]

stacks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('pages.urls')),
    path('', include('cards.urls')),
    path('', include('allauth.urls')),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cards/forms.py
from django import forms
from django.forms import formset_factory


class DeckForm(forms.Form):
    CHOICES = (
        ("Private", "Private"),
        ('Sec 1', 'Sec 1'),
        ('Sec 2', 'Sec 2'),
        ('Sec 3', 'Sec 3'),
        ('Sec 4', 'Sec 4'),
        ('J1', 'J1'),
        ('J2', 'J2'),
        ('Public', 'Public'),
        ('Teacher', 'Teacher'),
    )

    title = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'title',
               'placeholder': 'Title'}),
        label='')
    subject = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'subject',
               'placeholder': 'Subject'
               }),
        label='')
    availability = forms.ChoiceField(
        choices=CHOICES,
        widget=forms.Select(attrs={'class': 'choices'}),
        label=''
    )


class CardsForm(forms.Form):
    questionText = forms.CharField(widget=forms.Textarea(
        attrs={'class': 'questionText',
               'placeholder': 'Enter your question'
               }),
        label='')
    answerText = forms.CharField(widget=forms.Textarea(
        attrs={'class': 'answerText',
               'placeholder': 'Enter your answer'
               }),
        label='')
    answerImage = forms.ImageField(required=False,
                                   label='',
                                   widget=forms.ClearableFileInput(
                                       attrs={
                                           'class': 'answerImage',
                                       })
                                   )


CardsFormset = formset_factory(CardsForm, extra=250)


class ExcelUploadForm(forms.Form):
    excelForm = forms.FileField(label='')

templates/pages/add_users.html
{% extends "basedashboard.html" %} 
{% load static %} 
{% block style %}
<link href='{% static "/css/add_users.css" %}' rel="stylesheet" />
{% endblock %}
{% block content %}
<form enctype="multipart/form-data" action="" method="POST">
	{% csrf_token %}
  <div id="container">

    <div id="excelsheet">
      <p id="text">Click icon to upload excel file</p>
	    <label id="custom_upload" for="id_excelForm">
      <svg
        class="fileUpload"
        xmlns="http://www.w3.org/2000/svg"
        width="34.826"
        height="43.958"
        viewBox="0 0 34.826 43.958"
      >
        <g transform="translate(-0.5)">
          <path
            d="M24.188.34A1.063,1.063,0,0,0,
	23.424,0H6.276A5.8,5.8,0,0,0,.5,5.765V38.192a5.8,
	5.8,0,0,0,5.776,5.766H29.55a5.8,5.8,0,0,0,
	5.776-5.766V12.444a1.143,1.143,0,0,0-.308-.743ZM24.5,
	3.748l7.252,7.613H27.034A2.529,2.529,0,0,1,24.5,
	8.834ZM29.55,41.834H6.276a3.678,3.678,0,0,1-3.653-3.642V5.765A3.678,
	3.678,0,0,1,6.276,2.124h16.1v6.71a4.645,4.645,0,0,0,
	4.661,4.651H33.2V38.192A3.671,3.671,0,0,1,29.55,41.834Zm0,0"
          />
          <path
            d="M107.711,401.934H90.234a1.062,1.062,0,0,0,0,
	2.124h17.488a1.062,1.062,0,1,0-.011-2.124Zm0,0"
            transform="translate(-81.059 -367.426)"
          />
          <path
            d="M120.238,178.759l4.375-4.7V185.65a1.062,1.062,
	0,0,0,2.124,0V174.055l4.375,4.7a1.059,1.059,0,0,0,
	1.55-1.444l-6.222-6.679a1.054,1.054,0,0,0-1.55,0l-6.222,
	6.679a1.058,1.058,0,0,0,.053,1.5A1.083,1.083,0,0,
	0,120.238,178.759Zm0,0"
            transform="translate(-107.761 -155.676)"
          />
        </g>
      </svg>
      </label>
	    {{excel_form}}
    </div><!-- end of excelsheet-->

    <div id="deckForm">
    </div> <!-- end of deckform-->

    <div id="submitDiv">
	    <input type='submit' value='Submit' id="submit">
    </div> <!-- end of submit-->

  </div> <!-- end of container -->
</form>
	<script>
		var user_profile = "{{user_profile}}"
console.log(user_profile);
	</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src='{% static "/js/add_users.js" %}'></script>
{% endblock %}

templates/pages/change_password.html
{% extends "basedashboard.html" %}
{% load static %}
{% load cards_extra %}
{% block style %}
 <link href='{% static "/css/change_password.css" %}' rel="stylesheet">
{% endblock %}
{% block content %}
<form method="POST">
	{% csrf_token %}
	{{form}}
	<input class="change_button" type="submit" value="Change Password">
</form>
{% endblock %}

templates/pages/logout.html
{% extends "basedashboard.html" %}
{% load static %}
{% load cards_extra %}
{% block style %}
 <link href='{% static "/css/logout.css" %}' rel="stylesheet">
{% endblock %}
{% block content %}
<div id='userInfo'>
	<div id='user_name'>{{full_name}}</div>
	<div id='user_account'>{{profile}}</div>
	<div id='user_name'>{{user.email}}</div>
</div>
<div id='profile_logout_form_container'>
        <form id="profile_logout_form" method='POST' action="{% url 'account_logout' %}">
		{% csrf_token %}
		<input type="submit" class='profile_buttons' id='profile_logout' value="Logout">
	</form>
	<div id='change_password'>
		<a href="{% url 'change_password' %}" id="change_password">
		<input type="submit" class='profile_buttons' id='profile_logout' value="Change Password">
	</a>
	</div>
	{% if profile == "Teacher Account" %}
	<div id='profile_bulk_user'>
		<a href="{% url 'add_users' %}" id="profile_logout_form">
		<input type="submit" class='profile_buttons' id='profile_logout' value="Add Users">
	</a>
	</div>
</div>
{% endif %}
{% endblock %}